import openai
 
client = openai.Client(base_url="http://localhost:8123/v1", api_key="None")

response = client.chat.completions.create(
    model="Llama-3-8B-Instruct-QServe",
    messages=[
        {"role": "user", "content": "Please introduce yourself."},
    ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    max_tokens=100,
)
print(response.choices[0].message.content)
